### PR TITLE
Add Mhd writing

### PR DESCRIPTION
**Pull request by K-Meech**
- Copied mhd writer - https://github.com/embl-cba/elastixWrapper/blob/master/src/main/java/de/embl/cba/elastixwrapper/metaimage/MetaImage_Writer.java#L207 

- Added mhd writing to BdvRealSourceToVoxelImageExporter

- Added option to set names for sources

### CODE REVIEW

**Comment by K-Meech** [comment]
I'm changing a few other parts so hang on with this. I'll ping you when I'm finished.

**Comment by tischi** [comment]
I am sorry, but with the new imagej-utils there will probably be nasty merge conflicts :-(

Probably the easiest you start from the new imagej-utils and then copy your changes into it (from your current branch).

sorry

**Comment by tischi** [comment]
@K-Meech seeing the kind of mess that imagej-utils is I am thinking now we should make a separate repository for the mhd writer and reader. I made an empty repository: https://github.com/embl-cba/metaimage-io and gave you write access.

**Comment by K-Meech** [comment]
Ok - no problem! I'll move this over to that repository.

**Pull request closed without merging**
